language: python
python:
  - "2.7"
  #- "3.5"

branches:
  only:
    #- master
    - develop

cache:
  directories:
    - /usr/local/freesurfer
    - $HOME/.cache/pip

before_install:
  - sudo apt-get update
  - bash <(wget -q -O- http://neuro.debian.net/_files/neurodebian-travis.sh)
  - sudo apt-get -y update && sudo apt-get install -y -qq fsl-core afni tcsh bc
  - source /etc/fsl/fsl.sh
  - export PATH="/usr/lib/afni/bin/:$PATH"
  - export FSLOUTPUTTYPE=NIFTI_GZ
  - sudo bash install_freesurfer.sh
  - export FREESURFER_HOME=/usr/local/freesurfer
  - source $FREESURFER_HOME/SetUpFreeSurfer.sh
  - sudo cp license.txt $FREESURFER_HOME
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda config --add channels conda-forge
  - conda install --yes python=$TRAVIS_PYTHON_VERSION pip scipy numpy pandas scikit-learn
  - pip install nibabel nipype pytest pytest-cov coveralls pytest-pep8 future configparser

install:
  - python setup.py install

script:
  - bash run_tests.sh

after_success:
    # test coveralls
    - coveralls
